var restaurants = [
    '坐・和民',
    '三代目鳥メロ',
    '三代目 鳥メロ',
    'ミライザカ',
    'ちゃぶまる',
    'にくスタ',
    '炭旬',
    '旬八',
    'ニッポンまぐろ漁業団',
    '炉ばたや銀政',
    '銀政',
    '海のめぐみ食堂',
    'CHINA BISTRO WANG\'S GARDEN',
    'BARU & DINING GOHAN',
    'DON PORCO',
    'わたみん家',
    'GOHAN',
    'TGIFRIDAYS',
    'TGI Fridays',
    'TGIフライデーズ',
    'TGI フライデーズ',
    'WANG\'S GARDEN',
    'WANG\’S GARDEN',
    'TEX MEX FACTORY',
    '饗の屋',
    '和っしょい',
    '炭右衛門',
    'トリフェス',
    '渡美',
    '和民'
];